### PR TITLE
Prevent interrupt/kill from leaving broken cache

### LINKED ISSUE #121: Ctrl-C or crashing during build/watch/test can result in unusable cache that will never complete
Presently the only way to fix this is to clean the project and build again, but the plugin should detect this case as best it can and start the task over instead of waiting forever for the other process that originally started the work to finish it.

Several degrees of mitigation, with some assumptions:
 * The process that started the work should somehow mark that it is still running, for example by touching the cache entry directory every 1s or so. If another process detects that the directory is stale by some amount (5s, for example?) we could then assume it to have failed, try to delete it, and start again. Failure mode, on windows the other process might merely be stuck (gc, debugger, etc) and have locked some contents and prevent it from being deleted, the deleting process could either assume it is still being built, or just error out. This would need to be implemented as another thread in the scheduler watching one or more tasks as they work, touching the directories periodically.
 * Separately, a shutdown hook should be added as part of the scheduler, so that on shutdowns where work was in progress, that work should be stopped in some way, or have its output deleted to allow a later build to take over for it. This can also fail if that other process is still trying to finish its work, the shutdown hook can warn if delete fails and inform the user they may need to perform a clean.
 * Finally the DiskCache should detect a directory being deleted while running, and use that to signal that this process should attempt to own that task and start it, allowing one process to halt and another to pick up after it. In order to correctly handle the shutdown hook, it should be shut down before the BuildScheduler is stopped, so a process doesn't try to take over during its own shutdown.

Probably replace "shutdown hook" above with Closable.close() so that the services themselves don't watch for shutdown, but maven or whatever else is using the services can shut them down in the appropriate order. This order in turn should be documented.

### PR DESCRIPTION
**Pull request by niloc132**
This pull request applies the three basic suggestions from #121, to ensure that a stopping process will either clean up after itself, or that other processes can detect a stale cache and cancel the work, start over.

This doesn't go so far as to cancel in-progress work, to permit watch mode to more quickly start a new build, but it should make this easier to write.

Testing process should include gracefully halting a build, halting it abruptly (i.e. kill -9), and testing that both a new process can start up and take over, or that a second process running in parallel can take over the cache correctly. Because this is an issue wracked with potential race conditions, many tests should be run to ensure that this is working correctly.

Fixes #121

### CODE REVIEW

File: build-caching/src/main/java/com/vertispan/j2cl/build/DiskCache.java [hunk 1]
```diff
@@ -127,6 +146,27 @@ private void checkForWork() {
...
+            runningTasks.forEach(path -> {
+                try {
+                    Files.setLastModifiedTime(path, FileTime.from(Instant.now()));
+                } catch (IOException e) {
+                    // race, probably the file was deleted, leaving it in the collection
+                    // for now, the failing task will cause the entry to be deleted.
+                }
+            });
+            try {
+                Thread.sleep(1000);
```
Comment (niloc132) [inline build-caching/src/main/java/com/vertispan/j2cl/build/DiskCache.java:166]: parameterize this

File: j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/BuildMojo.java [hunk 2]
```diff
@@ -230,6 +231,29 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
+                // first prevent new tasks from starting
+                executor.shutdown();
+
+                // next, make sure the disk cache doesn't try to pick up work - this will block on joining
+                // to the watching thread, so we ran shutdown above
+                diskCache.close();
+
+                // finally, interrupt running work and wait a short time for that to stop
+                executor.shutdownNow();
+                executor.awaitTermination(10, TimeUnit.SECONDS);
```
Comment (niloc132) [inline j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/BuildMojo.java:245]: parameterize this for quicker shutdowns

**Comment by niloc132** [comment]
Bug still present: with two processes running, if one fails to completely clean its own canceled task, the other may not discover it to be stale. Presently planning to defer this to a later patch, and just address one process at a time.

**Review by treblereel — APPROVED** [review]
